[ 2025-09-03 10:07:54,604] 34 push_data.py - ERROR - 'str' object has no attribute 'values'
